authorizations: &AUTHORIZATIONS
  group_base: ou=groups,dc=fm,dc=test
  required_groups:
    - ["member", "cn=fleet-manager-users,ou=groups,dc=fm,dc=test"]
  admin_group: ["member", "cn=fleet-manager-admins,ou=groups,dc=fm,dc=test"]
   
development:
  host: localhost
  port: 389
  attribute: cn
  base: ou=users,dc=fm,dc=test
  admin_user: cn=fm_ldap,ou=users,dc=fm,dc=test
  admin_password: fm_ldap
  ssl: false
  <<: *AUTHORIZATIONS

test:
  host: localhost
  port: 389
  attribute: cn
  base: ou=users,dc=fm,dc=test
  admin_user: cn=fm_ldap,ou=users,dc=fm,dc=test
  admin_password: fm_ldap
  ssl: false
  <<: *AUTHORIZATIONS

production:
  host: fm.internal
  port: 636
  attribute: samaccountname
  base: cn=users,dc=fm,dc=internal
  admin_user: cn=fm_ldap,cn=users,dc=fm,dc=internal
  admin_password: fm_ldap
  ssl: start_tls
  <<: *AUTHORIZATIONS
