#!/bin/bash
### BEGIN INIT INFO
# Provides:          fml
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: FML Rails web app
# Description:       Enable FML service using Phusion Passenger.
#       Shamelessly cadged from https://gist.github.com/naholyr/4275302
### END INIT INFO

APP=fml
APPPATH="/srv/rails/$APP"
PIDFILE="/var/run/$APP.pid"
LOGFILE="/var/log/$APP.log"
PORT=443
SSL_CERT=/etc/ssl/certs/self-signed.pem
SSL_KEY=/etc/ssl/private/self-signed.key
USER=fml

SCRIPT="cd $APPPATH; passenger start -p $PORT --environment production --ssl --ssl-certificate $SSL_CERT --ssl-certificate-key $SSL_KEY --daemonize --user $USER --log-file $LOGFILE --pid-file $PIDFILE"

start() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo "Service already running" >&2
    return 1
  fi
  echo "Starting service…" >&2
  su -c "$SCRIPT"
  echo "Service started" >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo "Service not running" >&2
    return 1
  fi
  echo "Stopping service…" >&2
  passenger stop --pid-file $PIDFILE && rm -f "$PIDFILE"
  echo "Service stopped" >&2
}

status() {
  passenger status --pid-file $PIDFILE
}

if [[ $EUID -ne 0 ]]; then
  echo "You must be root" 2>&1
  exit 1
else
  case "$1" in
    status)
      status
      ;;
    start)
      start
      ;;
    stop)
      stop
      ;;
    restart)
      stop
      start
      ;;
    *)
      echo "Usage: $0 {status|start|stop|restart}"
  esac
fi
